### Create user
POST http://localhost:3000/user
Accept: application/json
Content-Type: application/json

{
  "name": "Elvis Presley",
  "email": "elvispresley@example.com",
  "age": 77
}

### Update user
PUT http://localhost:3000/user
Accept: application/json
Content-Type: application/json

{
  "id": "673fc62215c1600020135880",
  "name": "John Doe1",
  "email": "john@example.com",
  "age": 18
}


### Comment
POST http://localhost:3000/comment
Accept: application/json
Content-Type: application/json

{
  "content": "This is a comment",
  "userId": "6721b735c3128c0054ad0d07"
}

### Get comments
GET http://localhost:3000/user/673fc62215c1600020135880/comments

### Create comments
POST http://localhost:3000/comments/create-comments
Accept: application/json
Content-Type: application/json

[
  {
    "content": "First-first11 comment",
    "userId": "673fc62215c1600020135880"
  },
  {
    "content": "Second-second22 comment",
    "userId": "673fc62215c1600020135880"
  }
]


### Update comments
PUT http://localhost:3000/comments/update-comments
Accept: application/json
Content-Type: application/json

[
  {
    "content": "First-first-first (updated)",
    "_id": "673fc94e6f6f35004553fd26"
  }
]



